Update configurator for CMake.

diff --git a/bin/configurator b/bin/configurator
--- a/bin/configurator
+++ b/bin/configurator
@@ -4,8 +4,8 @@
 # packages on Linux from their respective sources.
 #
 # Tips:
-#   1. Use `time make -O -j2` to build.
-#   1. Use `make install-strip` to install.
+#   1. Use `time make -O -j2` or `time ninja -j2` to build.
+#   2. Use `make install-strip` or `ninja install/strip` to install.
 set -euo pipefail
 
 NAME="generic_autotools"
@@ -13,6 +13,7 @@ SOURCE="${PWD}"
 PREFIX="/usr"
 SYSCONF="/etc"
 
+CMAKE="${CMAKE:-/usr/bin/cmake}"
 MESON="${MESON:-/usr/bin/meson}"
 
 #
@@ -28,6 +29,20 @@ usage() {
 chk_configure() {
     if [[ ! -x "${SOURCE}/configure" ]]; then
         echo "ERROR: Missing \"configure\" script in \"${SOURCE}\"."
+        exit 1
+    fi
+}
+
+chk_cmake() {
+    if [[ ! -x "${CMAKE}" ]]; then
+        echo "ERROR: Unable to execute \"${CMAKE}\"."
+        exit 1
+    fi
+}
+
+chk_cmake_lists() {
+    if [[ ! -r "${PWD}/CMakeLists.txt" ]]; then
+        echo "ERROR: Missing \"CMakeLists.txt\" script in \"${PWD}\"."
         exit 1
     fi
 }
@@ -117,8 +132,9 @@ cfg_freetype() {
 #      for some pointers.
 cfg_ffmpeg() {
     chk_configure
-    (set -x; PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:/usr/lib/pkgconfig" \
-        "${SOURCE}/configure" --prefix="${PREFIX}" --disable-debug \
+    FFM_PREFIX="/opt/mm"
+    (set -x; PKG_CONFIG_PATH="${FFM_PREFIX}/lib/pkgconfig:/usr/lib/pkgconfig" \
+        "${SOURCE}/configure" --prefix="${FFM_PREFIX}" --disable-debug \
         --enable-shared --disable-static --disable-doc --disable-htmlpages \
         --enable-gpl --enable-version3 --enable-nonfree --disable-encoders \
         --enable-postproc --enable-avfilter --enable-swresample \
@@ -128,8 +144,9 @@ cfg_ffmpeg() {
         --x86asmexe=nasm --enable-optimizations --enable-stripping \
         --enable-libfdk-aac --enable-libdav1d --enable-libvpx \
         --enable-libx264 --enable-libx265 --enable-librsvg \
-        --extra-cflags="-I${PREFIX}/include" \
-        --extra-cxxflags="-I${PREFIX}/include" --extra-libs="-L${PREFIX}/lib" \
+        --extra-cflags="-I${FFM_PREFIX}/include" \
+        --extra-cxxflags="-I${FFM_PREFIX}/include" \
+        --extra-libs="-L${FFM_PREFIX}/lib" \
         "$@")
 }
 
@@ -170,6 +187,16 @@ cfg_generic_autotools() {
     (set -x; "${SOURCE}/configure" --prefix="${PREFIX}" \
         --sysconfdir="${SYSCONF}" --disable-static --enable-shared \
         --disable-debug --disable-nls "$@")
+}
+
+cfg_generic_cmake() {
+    chk_cmake
+    chk_cmake_lists
+    mkdir -p build && cd build && \
+        "${CMAKE}" -G "Ninja" -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
+            -DCMAKE_INSTALL_SYSCONFDIR="${SYSCONF}" \
+            -DCMAKE_BUILD_TYPE="Release" -DBUILD_SHARED_LIBS="ON" \
+            -DBUILD_STATIC_LIBS="OFF" "$@" "${SOURCE}"
 }
 
 cfg_generic_meson() {
@@ -443,15 +470,17 @@ cfg_vim() {
 #        http://solar.gmu.edu/meetings/cdaw/data/cdaw1/xine/share/doc/xine/README_xxmc.html
 cfg_xine_lib() {
     chk_configure
-    export CFLAGS="-march=pentium3 -msse -fomit-frame-pointer -pipe -g0 -O3 -I\"${PREFIX}/include\""
+    XINE_PREFIX="/opt/mm"
+    export CFLAGS="-march=pentium3 -msse -fomit-frame-pointer -pipe -g0"
+    export CFLAGS="${CFLAGS} -O3 -I\"${XINE_PREFIX}/include\""
     export CC="gcc ${CFLAGS}"
     export CPPFLAGS="${CFLAGS}"
     export CXX="g++ ${CPPFLAGS}"
-    export LDFLAGS="-L\"${PREFIX}/lib\""
-    export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:/usr/lib/pkgconfig"
+    export LDFLAGS="-L\"${XINE_PREFIX}/lib\""
+    export PKG_CONFIG_PATH="${XINE_PREFIX}/lib/pkgconfig:/usr/lib/pkgconfig"
     # Get from http://www.mplayerhq.hu/MPlayer/releases/codecs/
     W32CODECS="/usr/local/w32codecs"
-    (set -x; "${SOURCE}/configure" --prefix="${PREFIX}" \
+    (set -x; "${SOURCE}/configure" --prefix="${XINE_PREFIX}" \
         --sysconfdir="${SYSCONF}" --disable-static --enable-shared \
         --disable-profiling --disable-debug --disable-nls --disable-asan \
         --disable-iconvtest --disable-ipv6 --disable-wayland --disable-aalib \
@@ -469,14 +498,15 @@ cfg_xine_lib() {
 # xine-ui-0.99.12
 cfg_xine_ui() {
     chk_configure
-    export PATH="${PREFIX}/bin:${PATH}"
-    export CFLAGS="-march=pentium3 -msse -pipe -g0 -I\"${PREFIX}/include\""
+    XINE_PREFIX="/opt/mm"
+    export PATH="${XINE_PREFIX}/bin:${PATH}"
+    export CFLAGS="-march=pentium3 -msse -pipe -g0 -I\"${XINE_PREFIX}/include\""
     export CC="gcc ${CFLAGS}"
     export CPPFLAGS="${CFLAGS}"
     export CXX="g++ ${CPPFLAGS}"
-    export LDFLAGS="-L\"${PREFIX}/lib\""
-    export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:/usr/lib/pkgconfig"
-    (set -x; "${SOURCE}/configure" --prefix="${PREFIX}" \
+    export LDFLAGS="-L\"${XINE_PREFIX}/lib\""
+    export PKG_CONFIG_PATH="${XINE_PREFIX}/lib/pkgconfig:/usr/lib/pkgconfig"
+    (set -x; "${SOURCE}/configure" --prefix="${XINE_PREFIX}" \
         --sysconfdir="${SYSCONF}" --disable-debug --disable-nls --enable-xft \
         "$@")
 }
@@ -504,13 +534,21 @@ cfg_xorg_server() {
 # xorg-server-1.12.4
 #
 # NOTE: The last version of the Xorg server compatible with the proprietary
-# nVidia Linux 32-bit driver v96.43.23. Use with Linux Kernel v2.6.39.4.
+# Nvidia Linux 32-bit driver v96.43.23.
 #
-# NOTE: Apply the patch from:
-#   http://lists.busybox.net/pipermail/buildroot/2015-June/130276.html
-# using:
-#   patch -p1 -b -z .orig -i ../xsrv112gcc5.patch
-# to get this to compiler with GCC v5+.
+# NOTE:
+#   1. Apply the patch from:
+#        http://lists.busybox.net/pipermail/buildroot/2015-June/130276.html
+#      using:
+#        patch -p1 -b -z .orig -i ../xsrv112gcc5.patch
+#      to get this to compiler with GCC v5+.
+#   2. This assumes OpenGL headers as defined by Khronos/Mesa. Be sure to
+#      install the legacy Nvidia driver with "--no-opengl-headers" or repair
+#      the damage later by replacing the folowing headers with those from Mesa:
+#        /usr/include/GL/gl.h
+#        /usr/include/GL/glext.h
+#        /usr/include/GL/glx.h
+#        /usr/include/GL/glxext.h
 cfg_xorg_server_legacy() {
     chk_configure
     (set -x; "${SOURCE}/configure" --prefix="${PREFIX}" \
@@ -583,6 +621,9 @@ case "${NAME}" in
         ;;
     generic_autotools)
         cfg_generic_autotools "$@"
+        ;;
+    generic_cmake)
+        cfg_generic_cmake "$@"
         ;;
     generic_meson)
         cfg_generic_meson "$@"
