Retire the remaining per-program build-scripts.

diff --git a/bin/git b/bin/git
--- a/bin/git
+++ b/bin/git
@@ -1,21 +1,15 @@
-#!/usr/bin/env bash
+#!/usr/bin/dash
 # Create a shell-alias to point to this wrapper over the "git" command.
 #
 # NOTE: We do *not* create a symbolic-link in $HOME/bin as usual - the Makefile
 # in git-2.20, for example, tries to execute the "git rev-parse" command, gets
 # confused by the error-message from this wrapper, and causes build-errors.
-set -o nounset
-set -o errexit
-set -o pipefail
+set -eu
 
-GIT_BASE="/usr/local/git"
-if [[ ! -x "${GIT_BASE}/bin/git" ]]
-then
-    echo ERROR: Unable to execute \"${GIT_BASE}/bin/git\".
+GIT_PREFIX="/opt/git"
+if [ ! -x "${GIT_PREFIX}/bin/git" ]; then
+    echo "ERROR: Unable to execute \"${GIT_PREFIX}/bin/git\"."
     exit 1
 fi
-if [[ ! "${MANPATH}" =~ ".*${GIT_BASE}/share/man.*" ]]
-then
-    export MANPATH="${GIT_BASE}/share/man:${MANPATH}"
-fi
-"${GIT_BASE}/bin/git" --no-pager "$@"
+export MANPATH="${GIT_PREFIX}/share/man:${MANPATH}"
+"${GIT_PREFIX}/bin/git" --no-pager "$@"
